EMAIL_MAX_LENGTH = 254
USERNAME_REGEX = r'^[\w.@+-]+\Z'
USERNAME_MAX_LENGTH = 150

NAME_MAX_LENGTH = 256
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150

MEASUREMENT_UNIT_LENGTH = 256
TAG_LENGTH = 256
SLUG_LENGTH = 256

СOOKING_TIME_MIN = 1
СOOKING_TIME_MAX = 720

AMOUNT_INGREDIENT_MIN = 1
AMOUNT_INGREDIENT_MAX = 50

LIMIT_PAGE_SIZE = 6
