# Generated by Django 3.2.3 on 2025-03-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
